create table if not exists public.profiles (
  id uuid not null,
  name text,
  role text not null default 'staff'::text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  position text,
  phone text,
  constraint profiles_pkey primary key (id),
  constraint profiles_role_check check ((role = any (array['admin'::text, 'staff'::text])))
);

-- Export metadata confirmed profiles_id_fkey exists; target was inferred to auth.users(id).
do $$
begin
  if not exists (
    select 1
    from pg_constraint
    where conname = 'profiles_id_fkey'
      and connamespace = 'public'::regnamespace
  ) then
    alter table public.profiles
      add constraint profiles_id_fkey
      foreign key (id)
      references auth.users (id)
      on delete cascade;
  end if;
end
$$;

create table if not exists public.properties (
  id uuid not null default gen_random_uuid(),
  global_id text not null,
  item_no text not null,
  source_type public.source_type not null,
  is_general boolean not null default false,
  address text not null,
  asset_type text,
  exclusive_area numeric,
  common_area numeric,
  site_area numeric,
  use_approval date,
  status text,
  price_main numeric,
  date_main timestamp with time zone,
  source_url text,
  memo text,
  latitude double precision,
  longitude double precision,
  date_uploaded timestamp with time zone not null default now(),
  assignee_id uuid,
  raw jsonb,
  geocode_status text,
  geocode_provider text,
  geocode_updated_at timestamp with time zone,
  geocode_query_address text,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  submitter_type public.submitter_type,
  submitter_name text,
  submitter_phone text,
  broker_office_name text,
  broker_name text,
  broker_license_no text,
  geocoded_at timestamp with time zone,
  registration_identity_key text,
  registration_identity_key_v2 text,
  registration_identity_confidence text,
  source text,
  lowprice numeric,
  floor text,
  total_floor text,
  assignee_name text,
  rights_analysis text,
  site_inspection text,
  daily_issue text,
  constraint properties_pkey primary key (id),
  constraint properties_assignee_id_fkey
    foreign key (assignee_id)
    references public.profiles (id)
);

create table if not exists public.property_activity_logs (
  id bigint generated by default as identity not null,
  property_id text,
  property_identity_key text,
  property_item_no text,
  property_address text,
  actor_id uuid not null,
  actor_name text,
  action_type text not null,
  action_date date not null,
  changed_fields jsonb not null default '[]'::jsonb,
  note text,
  created_at timestamp with time zone not null default now(),
  constraint property_activity_logs_pkey primary key (id)
);

create table if not exists public.property_photos (
  id uuid not null default gen_random_uuid(),
  property_id text not null,
  property_global_id text,
  storage_path text not null,
  thumb_path text not null,
  mime_type text,
  width integer,
  height integer,
  size_bytes bigint,
  sort_order integer not null default 0,
  is_primary boolean not null default false,
  uploaded_by uuid,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  deleted_at timestamp with time zone,
  constraint property_photos_pkey primary key (id)
);
